1.1.3 rc
tonlabs/everdev pull request #109
Opened 2022-05-26 13:50 UTC by Artem-Zhdanov

Changes:
 1. Now it is possible to compile several files, e.g:
 ```
node cli.js sol create dir1/Contract1 
node cli.js sol create dir1/Contract2 

node cli.js sol compile dir1/*.sol
// or
node cli.js sol compile dir1/Contact1.sol   dir1/Contact2.sol
// or 
node cli.js sol compile dir1/*.sol  --output-dir dir2
```
2. Add command everdev contract decode-account-data, e.g:
```
node cli.js contract decode-account-data HelloWallet.abi.json  -a 0:783abd8b2cbcc578397d8d15ae8293688a87da15a052a993cfb51cbd3e6452a3

Configuration

  Network: nettondev (https://gra01.net.everos.dev)
  Signer:  giver_net_keys (public 95c06aa743d1f9000dd64b75498f106af4b7e7444234d7de67ea26988f6181df)

Address:   0:783abd8b2cbcc578397d8d15ae8293688a87da15a052a993cfb51cbd3e6452a3
Decoded account data: {
    "data": {
        "_pubkey": "0x95c06aa743d1f9000dd64b75498f106af4b7e7444234d7de67ea26988f6181df",
        "_timestamp": "1653482490973",
        "_constructorFlag": true,
        "timestamp": "1653482492"
    }
}
```
3. Add command everdev contract decode-tvc, e.g: 
```
node cli.js contract decode-tvc HelloWallet.tvc
Decoded TVC: {
"code": "te6ccgEC4Q/hCyMv/yz/Pg8sfye1UAQKIEwAUasfye1UAQKIEwAUaGVsbG9Xb3JsZAAK+Eby4EwCCvSkIPShFxYAFHNvbCAwLjYxLjAAAA==",
"code_hash": "7a588d25395138fa12f9fd358b2383922b80a2dcbc973cd437723b4d96c9ae13",
"code_depth": 6,
"data": "te6ccgEBAgEAKAABAcABAEPQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAg",
"data_hash": "55a703465a160dce20481375de2e5b830c841c2787303835eb5821d62d65ca9d",
"data_depth": 1,
"library": null,
"tick": null,
"tock": null,
"split_depth": null,
"compiler_version": "sol 0.61.0"
}```

2022-05-27 12:04 UTC, elasticLove1 requested changes
update version to 1.2.0
rename decode-account-data into decode-data
donor -> giver :)

2022-05-27 12:06 UTC, elasticLove1 requested changes
Add documentation about decode-data and decode-tvc functions

2022-05-27 12:22 UTC, elasticLove1 approved these changes

2022-05-30 08:17 UTC, d3p approved these changes

2022-05-30 08:34 UTC, merged